server:
  port: 8080

spring:
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: env,health,info

file:
  hash-algorithm: SHA-256
  upload-dir: /app/uploads
  # Octal POSIX permissions for upload subdirectories
  sub-dirs-perms: 775
  sub-dirs:
    offer-previews: offers
    books-images: books
    #user-avatars: user-avatars